import type { ActionTimelineEntry, ReportableError } from '@open-codesign/shared';
import { describe, expect, it } from 'vitest';
import {
  type SummaryInput,
  composeSummaryMarkdown,
  mdInlineCode,
  redactPathsAndUrls,
} from './diagnostic-summary';

function baseEvent(overrides: Partial<ReportableError> = {}): ReportableError {
  return {
    localId: 'local-1',
    ts: Date.UTC(2026, 0, 1, 12, 0, 0),
    code: 'E_PROVIDER_TIMEOUT',
    scope: 'provider',
    runId: 'run-abc',
    fingerprint: 'deadbeef',
    message: 'Request timed out',
    ...overrides,
  };
}

function baseInput(overrides: Partial<SummaryInput> = {}): SummaryInput {
  return {
    error: baseEvent(),
    count: 3,
    level: 'error',
    transient: false,
    appVersion: '0.4.0',
    platform: 'darwin-arm64',
    electronVersion: '33.2.1',
    nodeVersion: '22.11.0',
    timeline: [],
    recentLogTail: ['[00:00] hello', '[00:01] world'],
    notes: '',
    includePromptText: true,
    includePaths: true,
    includeUrls: true,
    includeTimeline: true,
    ...overrides,
  };
}

describe('composeSummaryMarkdown', () => {
  it('renders header, environment, and "(no stack)" when stack is undefined', () => {
    const md = composeSummaryMarkdown(baseInput());
    expect(md).toContain('# Diagnostic Report — E_PROVIDER_TIMEOUT');
    expect(md).toContain('**Fingerprint:** `deadbeef`  (seen 3 times)');
    expect(md).toContain('**Run id:** `run-abc`');
    expect(md).toContain('- App: 0.4.0');
    expect(md).toContain('- Electron: 33.2.1 / Node: 22.11.0');
    expect(md).toContain('### Stack (top 5 frames)');
    expect(md).toContain('(no stack)');
    expect(md).toContain('(none)');
    expect(md).toContain('Generated by open-codesign 0.4.0.');
  });

  it('renders top 5 frames normalized from a real stack', () => {
    const stack = [
      'Error: boom',
      '    at generate (/Users/alice/code/pkg/src/index.ts:482:11)',
      '    at Object.submit (/Users/alice/code/pkg/src/submit.ts:10:3)',
      '    at step (/Users/alice/code/pkg/src/step.ts:1:1)',
      '    at a (/x/a.ts:1:1)',
      '    at b (/x/b.ts:1:1)',
      '    at c (/x/c.ts:1:1)',
      '    at d (/x/d.ts:1:1)',
    ].join('\n');
    const md = composeSummaryMarkdown(baseInput({ error: baseEvent({ stack }) }));
    expect(md).toContain('at generate (index.ts)');
    expect(md).toContain('at Object.submit (submit.ts)');
    expect(md).toContain('at step (step.ts)');
    expect(md).toContain('at a (a.ts)');
    expect(md).toContain('at b (b.ts)');
    expect(md).not.toContain('at c (c.ts)');
  });

  it('stack with paren-less frames is redacted when includePaths=false', () => {
    const stack = [
      'Error: top-level',
      '    at /Users/hq/Documents/Github/codesign/dist/main.js:12:7',
    ].join('\n');
    const md = composeSummaryMarkdown(
      baseInput({ error: baseEvent({ stack }), includePaths: false }),
    );
    expect(md).not.toContain('/Users/hq');
    expect(md).not.toContain('/dist/main.js');
  });

  it('renders timeline as a table with relative-second offsets newest-first', () => {
    const eventTs = Date.UTC(2026, 0, 1, 12, 0, 0);
    const timeline: ActionTimelineEntry[] = [
      { ts: eventTs - 42_000, type: 'prompt.submit', data: { promptLen: 312 } },
      { ts: eventTs - 12_000, type: 'prompt.cancel' },
      { ts: eventTs - 30_000, type: 'provider.switch', data: { to: 'anthropic' } },
    ];
    const md = composeSummaryMarkdown(baseInput({ error: baseEvent({ ts: eventTs }), timeline }));
    expect(md).toContain('| Offset | Type | Details |');
    const tableStart = md.indexOf('| -12 s |');
    const middle = md.indexOf('| -30 s |');
    const last = md.indexOf('| -42 s |');
    expect(tableStart).toBeGreaterThan(-1);
    expect(tableStart).toBeLessThan(middle);
    expect(middle).toBeLessThan(last);
    expect(md).toContain('promptLen=312');
    expect(md).toContain('| -12 s | prompt.cancel | — |');
  });

  it('omits timeline when includeTimeline is false', () => {
    const md = composeSummaryMarkdown(baseInput({ includeTimeline: false }));
    expect(md).toContain('_(timeline omitted — user chose not to include)_');
    expect(md).not.toContain('| Offset | Type |');
  });

  it('timeline data is scrubbed for paths when includePaths=false', () => {
    const eventTs = Date.UTC(2026, 0, 1, 12, 0, 0);
    const timeline: ActionTimelineEntry[] = [
      {
        ts: eventTs - 1_000,
        type: 'design.open',
        data: { path: '/Users/alice/secret.md' } as unknown as Record<string, never>,
      },
    ];
    const md = composeSummaryMarkdown(
      baseInput({ error: baseEvent({ ts: eventTs }), timeline, includePaths: false }),
    );
    expect(md).not.toContain('/Users/alice/secret.md');
    expect(md).toContain('[path omitted]');
  });

  it('timeline data is scrubbed for prompt JSON when includePromptText=false', () => {
    const eventTs = Date.UTC(2026, 0, 1, 12, 0, 0);
    const timeline: ActionTimelineEntry[] = [
      {
        ts: eventTs - 1_000,
        type: 'prompt.submit',
        data: {
          payload: { prompt: 'super secret body' },
        } as unknown as Record<string, never>,
      },
    ];
    const md = composeSummaryMarkdown(
      baseInput({ error: baseEvent({ ts: eventTs }), timeline, includePromptText: false }),
    );
    expect(md).not.toContain('super secret body');
    expect(md).toContain('[prompt omitted]');
  });

  it('timeline data is scrubbed for urls when includeUrls=false', () => {
    const eventTs = Date.UTC(2026, 0, 1, 12, 0, 0);
    const timeline: ActionTimelineEntry[] = [
      {
        ts: eventTs - 1_000,
        type: 'provider.switch',
        data: { endpoint: 'https://example.com/private' } as unknown as Record<string, never>,
      },
    ];
    const md = composeSummaryMarkdown(
      baseInput({ error: baseEvent({ ts: eventTs }), timeline, includeUrls: false }),
    );
    expect(md).not.toContain('https://example.com/private');
    expect(md).toContain('[url omitted]');
  });

  it('renders upstream context for provider scope with all 4 fields', () => {
    const md = composeSummaryMarkdown(
      baseInput({
        error: baseEvent({
          scope: 'provider',
          context: {
            upstream_provider: 'anthropic',
            upstream_status: 504,
            upstream_request_id: 'req_123',
            retry_count: 2,
            redacted_body_head: '{"type":"error","message":"timeout"}',
          },
        }),
      }),
    );
    expect(md).toContain('### Upstream context');
    expect(md).toContain('- Provider: anthropic');
    expect(md).toContain('- Status: 504');
    expect(md).toContain('- Request-Id: req_123');
    expect(md).toContain('- Retry count: 2');
    expect(md).toContain('- Body head: {"type":"error","message":"timeout"}');
  });

  it('does not render upstream context for non-provider scope', () => {
    const md = composeSummaryMarkdown(
      baseInput({
        error: baseEvent({
          scope: 'ipc',
          context: { upstream_provider: 'anthropic' },
        }),
      }),
    );
    expect(md).not.toContain('### Upstream context');
  });

  it('redacts paths and URLs when includePaths/includeUrls are false', () => {
    const md = composeSummaryMarkdown(
      baseInput({
        error: baseEvent({
          message: 'Failed at /Users/alice/foo/bar.ts see https://example.com/x',
        }),
        recentLogTail: ['/Users/alice/app.log https://example.com/y'],
        includePaths: false,
        includeUrls: false,
      }),
    );
    expect(md).not.toContain('/Users/alice');
    expect(md).not.toContain('https://example.com');
    expect(md).toContain('[path omitted]');
    expect(md).toContain('[url omitted]');
  });

  it('redacts prompt-looking message when includePromptText is false', () => {
    const jsonPrompt = `generate.request data={"prompt":"${'x'.repeat(250)}"}`;
    const md = composeSummaryMarkdown(
      baseInput({
        error: baseEvent({ message: jsonPrompt }),
        includePromptText: false,
      }),
    );
    expect(md).toContain('[prompt omitted]');
    expect(md).not.toContain('x'.repeat(250));
  });

  it('preserves Chinese error message containing 请', () => {
    const longChinese = `请检查网络连接后重试。${'错'.repeat(300)}`;
    const md = composeSummaryMarkdown(
      baseInput({
        error: baseEvent({ message: longChinese }),
        includePromptText: false,
      }),
    );
    expect(md).not.toContain('[prompt omitted]');
    expect(md).toContain('请检查网络连接后重试');
  });

  it('log tail redacts prompt JSON when includePromptText=false', () => {
    const md = composeSummaryMarkdown(
      baseInput({
        recentLogTail: [
          '[00:00] generate.request data={"prompt":"help me build X","model":"sonnet"}',
          '[00:01] prompt: "another secret body"',
        ],
        includePromptText: false,
      }),
    );
    expect(md).not.toContain('help me build X');
    expect(md).not.toContain('another secret body');
    expect(md).toContain('[prompt omitted]');
    expect(md).toContain('"model":"sonnet"');
  });

  it('log tail preserves prompt content when includePromptText=true', () => {
    const md = composeSummaryMarkdown(
      baseInput({
        recentLogTail: ['[00:00] generate.request data={"prompt":"help me build X"}'],
        includePromptText: true,
      }),
    );
    expect(md).toContain('help me build X');
  });

  it('caps output at 20 KB with a truncation suffix', () => {
    const huge = 'a'.repeat(50_000);
    const md = composeSummaryMarkdown(baseInput({ notes: huge }));
    expect(new TextEncoder().encode(md).byteLength).toBeLessThanOrEqual(20 * 1024);
    expect(md).toMatch(/_\(summary truncated to 20 KB — full bundle attached as zip\)_$/);
  });

  it('renders "(none)" for blank or whitespace-only notes', () => {
    const md = composeSummaryMarkdown(baseInput({ notes: '   \n  ' }));
    expect(md).toContain('## Reporter notes\n(none)');
  });

  describe('path and URL redaction edge cases', () => {
    it('redacts Windows drive-letter paths', () => {
      const md = composeSummaryMarkdown(
        baseInput({
          error: baseEvent({ message: 'fail at C:\\Users\\alice\\project\\foo.ts line 10' }),
          includePaths: false,
        }),
      );
      expect(md).not.toContain('C:\\Users\\alice');
      expect(md).toContain('[path omitted]');
    });

    it('redacts Windows forward-slash drive-letter paths (Electron/Node style)', () => {
      const md = composeSummaryMarkdown(
        baseInput({
          error: baseEvent({ message: 'fail at C:/Users/alice/project/foo.ts line 10' }),
          includePaths: false,
        }),
      );
      expect(md).not.toContain('C:/Users/alice');
      expect(md).toContain('[path omitted]');
    });

    it('redacts UNC paths', () => {
      const md = composeSummaryMarkdown(
        baseInput({
          error: baseEvent({ message: 'read \\\\server\\share\\file.txt bad' }),
          includePaths: false,
        }),
      );
      expect(md).not.toContain('\\\\server\\share');
      expect(md).toContain('[path omitted]');
    });

    it('redacts ~/ home-relative paths', () => {
      const md = composeSummaryMarkdown(
        baseInput({
          error: baseEvent({ message: 'missing ~/foo/bar config' }),
          includePaths: false,
        }),
      );
      expect(md).not.toContain('~/foo/bar');
      expect(md).toContain('[path omitted]');
    });

    it('redacts /opt/homebrew and /root paths', () => {
      const md = composeSummaryMarkdown(
        baseInput({
          error: baseEvent({ message: 'install /opt/homebrew/bin/x then /root/cfg fails' }),
          includePaths: false,
        }),
      );
      expect(md).not.toContain('/opt/homebrew');
      expect(md).not.toContain('/root/cfg');
    });

    it('redacts file:// URLs when includeUrls=false', () => {
      const md = composeSummaryMarkdown(
        baseInput({
          error: baseEvent({ message: 'load file:///Users/x/data.json failed' }),
          includePaths: true,
          includeUrls: false,
        }),
      );
      expect(md).not.toContain('file:///Users/x');
      expect(md).toContain('[url omitted]');
    });

    it('redacts ws:// and wss:// URLs when includeUrls=false', () => {
      const md = composeSummaryMarkdown(
        baseInput({
          error: baseEvent({ message: 'ws://localhost:3000 down, wss://api.x.io/stream' }),
          includeUrls: false,
        }),
      );
      expect(md).not.toContain('ws://localhost');
      expect(md).not.toContain('wss://api.x.io');
    });

    it('does NOT redact dates or simple ratios as paths', () => {
      const md = composeSummaryMarkdown(
        baseInput({
          error: baseEvent({ message: 'on 2026/04/22 got 1/2/3 reasons' }),
          includePaths: false,
        }),
      );
      expect(md).toContain('2026/04/22');
      expect(md).toContain('1/2/3');
      expect(md).not.toContain('[path omitted]');
    });

    it('redacts macOS /var/folders temp paths', () => {
      const md = composeSummaryMarkdown(
        baseInput({
          error: baseEvent({ message: 'ENOENT /var/folders/xy/abc/T/cache broken' }),
          includePaths: false,
        }),
      );
      expect(md).not.toContain('/var/folders');
      expect(md).toContain('[path omitted]');
    });

    it('redacts /tmp paths', () => {
      const md = composeSummaryMarkdown(
        baseInput({
          error: baseEvent({ message: 'wrote /tmp/open-codesign-cache/foo then failed' }),
          includePaths: false,
        }),
      );
      expect(md).not.toContain('/tmp/open-codesign-cache');
      expect(md).toContain('[path omitted]');
    });

    it('redacts /etc paths', () => {
      const md = composeSummaryMarkdown(
        baseInput({
          error: baseEvent({ message: 'ENOENT /etc/hosts missing' }),
          includePaths: false,
        }),
      );
      expect(md).not.toContain('/etc/hosts');
      expect(md).toContain('[path omitted]');
    });

    it('redacts /private/var paths', () => {
      const md = composeSummaryMarkdown(
        baseInput({
          error: baseEvent({ message: 'failed at /private/var/folders/abc end' }),
          includePaths: false,
        }),
      );
      expect(md).not.toContain('/private/var');
      expect(md).toContain('[path omitted]');
    });

    it('does NOT redact API-style paths like generate/v1/endpoint', () => {
      const md = composeSummaryMarkdown(
        baseInput({
          error: baseEvent({ message: 'POST generate/v1/endpoint returned 500' }),
          includePaths: false,
        }),
      );
      expect(md).toContain('generate/v1/endpoint');
      expect(md).not.toContain('[path omitted]');
    });

    it('does NOT redact "10/30 ratio" style fractions', () => {
      const md = composeSummaryMarkdown(
        baseInput({
          error: baseEvent({ message: 'success 10/30 ratio observed' }),
          includePaths: false,
        }),
      );
      expect(md).toContain('10/30 ratio');
      expect(md).not.toContain('[path omitted]');
    });
  });
});

describe('redactPathsAndUrls granular toggles', () => {
  const sample = 'see /Users/alice/x.ts and https://example.com/y';

  it('redacts neither when both flags are true', () => {
    expect(redactPathsAndUrls(sample, { includePaths: true, includeUrls: true })).toBe(sample);
  });

  it('redacts only paths when includePaths=false, includeUrls=true', () => {
    const out = redactPathsAndUrls(sample, { includePaths: false, includeUrls: true });
    expect(out).not.toContain('/Users/alice');
    expect(out).toContain('https://example.com/y');
    expect(out).toContain('[path omitted]');
  });

  it('redacts only urls when includePaths=true, includeUrls=false', () => {
    const out = redactPathsAndUrls(sample, { includePaths: true, includeUrls: false });
    expect(out).toContain('/Users/alice/x.ts');
    expect(out).not.toContain('https://example.com');
    expect(out).toContain('[url omitted]');
  });

  it('redacts both when both flags are false', () => {
    const out = redactPathsAndUrls(sample, { includePaths: false, includeUrls: false });
    expect(out).toContain('[path omitted]');
    expect(out).toContain('[url omitted]');
  });
});

describe('mdInlineCode', () => {
  it('wraps a plain string in single backticks', () => {
    expect(mdInlineCode('hello world')).toBe('`hello world`');
  });

  it('escapes a single-backtick string by using double-backtick delimiters', () => {
    expect(mdInlineCode('has `tick` inside')).toBe('``has `tick` inside``');
  });

  it('picks a delimiter longer than the longest embedded run', () => {
    expect(mdInlineCode('pre ``` post')).toBe('````pre ``` post````');
  });

  it('pads when content starts or ends with a backtick', () => {
    expect(mdInlineCode('`leading')).toBe('`` `leading ``');
    expect(mdInlineCode('trailing`')).toBe('`` trailing` ``');
  });
});

describe('composeSummaryMarkdown — Message field backtick safety', () => {
  it('wraps Message in a code span even when it contains backticks, preserving Level and Transient', () => {
    const md = composeSummaryMarkdown(
      baseInput({
        error: baseEvent({ message: 'error at `foo.bar()` in handler' }),
      }),
    );
    expect(md).toContain('- Level: error');
    expect(md).toContain('- Transient (retried and succeeded): no');
    expect(md).toContain('- Message: ``error at `foo.bar()` in handler``');
  });

  it('still wraps a plain Message in a simple code span', () => {
    const md = composeSummaryMarkdown(baseInput());
    expect(md).toContain('- Message: `Request timed out`');
  });
});
